version: 2.1
orbs:
  node: circleci/node@2.0.2
executors:
  app-executor:
    docker:
      - image: circleci/node:15.0.1
    working_directory: ~/repo

aliases:
  - &show-current-branch-name
    run:
      name: Show Branch Name
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}
  - &install-pm2
    run:
      name: Install PM2
      command: npm install pm2
  - &install-dependencies
    run:
      name: Install Dependencies
      command: npm install
  - &deploy_to_heroku
    run:
      name: Deploy To deploy_to_heroku
      command: |
        if [ "${CIRCLE_BRANCH}" == "master" ]
        then
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/twitter-clone-node.git ${CIRCLE_BRANCH}:master -f
        else
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/twitter-clone-node.git ${CIRCLE_BRANCH}:master -f
        fi

jobs:
  build:
    executor: app-executor 
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *install-pm2
      - *save-cache
  deploy_to_heroku:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *deploy_to_heroku


workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_to_heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - master